-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGS*******CCqGSM49AwEHBHkwdwIBAQQgQAetDdWp5C1nYUnG
ZaygNzLXimFD*********lNt****CgYIKoZIzj0DAQehRANCAARPTlBY9eHN38qr
UlDXLy2w+vzJVBrifnNyJDgf0O3+********7zjOmNXUomKcj7eoqVS0gPtNcm2B
CQe*****
-----END PRIVATE KEY-----
